# Generated by Django 5.0.4 on 2024-10-01 09:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompressorUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evap_Entering_Water_Temp', models.CharField(blank=True, max_length=100, null=True)),
                ('Evap_Leaving_Water_Temp', models.CharField(blank=True, max_length=3, null=True)),
                ('Evap_Saturated_Rfgt_Temp', models.CharField(blank=True, max_length=15, null=True)),
                ('Evap_Saturated_Rfgt_Pres', models.CharField(blank=True, max_length=15, null=True)),
                ('Evap_Flowswitch_Status', models.CharField(blank=True, max_length=15, null=True)),
                ('Evap_Rfgt_Approach_Temp', models.CharField(blank=True, max_length=15, null=True)),
                ('Expansion_Valve_Position', models.CharField(blank=True, max_length=15, null=True)),
                ('Expansion_Valve_Steps', models.CharField(blank=True, max_length=15, null=True)),
                ('Evap_Rfgt_Liquid_Level', models.CharField(blank=True, max_length=15, null=True)),
                ('Evap_Water_PD_FT', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PM_system.compressorunit')),
            ],
        ),
    ]
