# Generated by Django 5.0.4 on 2024-10-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Entering_Water_Temp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Flowswitch_Status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Leaving_Water_Temp',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Rfgt_Approach_Temp',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Rfgt_Liquid_Level',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Saturated_Rfgt_Pres',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Saturated_Rfgt_Temp',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Water_PD_FT',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Expansion_Valve_Position',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Expansion_Valve_Steps',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
