# Generated by Django 5.0.4 on 2024-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_system', '0002_alter_compressor_evap_entering_water_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Water_PD_FT',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
