# Generated by Django 5.0.4 on 2024-11-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_system', '0004_compressor_avg_line_curr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressor',
            name='AVg_Line_Curr',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Chill_Water_Setpoint',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Curr_Lim_Setpoint',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Entering_Water_Temp',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Leaving_Water_Temp',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Rfgt_Approach_Temp',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Rfgt_Liquid_Level',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Saturated_Rfgt_Pres',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Saturated_Rfgt_Temp',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Water_PD_FT',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Expansion_Valve_Position',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Expansion_Valve_Steps',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
