# Generated by Django 6.1 on 2026-08-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_system', '0005_alter_compressor_avg_line_curr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressor',
            name='AVg_Line_Curr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Chill_Water_Setpoint',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Curr_Lim_Setpoint',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Entering_Water_Temp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Leaving_Water_Temp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Rfgt_Approach_Temp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Rfgt_Liquid_Level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Saturated_Rfgt_Pres',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Saturated_Rfgt_Temp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Evap_Water_PD_FT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Expansion_Valve_Position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='Expansion_Valve_Steps',
            field=models.IntegerField(null=True),
        ),
    ]
