# Generated by Django 6.1 on 2026-08-29 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_system', '0006_alter_compressor_avg_line_curr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
